//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigration.Data.V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMatch
    {
        public string Id { get; set; }
        public System.DateTime Date { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public int Level { get; set; }
        public string Country { get; set; }
        public int HtGoals { get; set; }
        public int AtGoals { get; set; }
        public string Season { get; set; }
    }
}
