//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigration.Data.V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public System.DateTime Date { get; set; }
        public int HomeTeamId { get; set; }
        public int AwayTeamId { get; set; }
        public int SeasonId { get; set; }
        public int LeagueId { get; set; }
        public int CountryId { get; set; }
        public byte HomeGoals { get; set; }
        public byte AwayGoals { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual League League { get; set; }
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
